#!/bin/bash

python "$OPENSHIFT_REPO_DIR"/manage.py migrate --noinput
python "$OPENSHIFT_REPO_DIR"/manage.py collectstatic --noinput

if [ ! -f ${OPENSHIFT_DATA_DIR}/CREDENTIALS ]; then
    python "$OPENSHIFT_REPO_DIR"/manage.py createsuperuser --username=admin --email=admin@localhost --noinput
    python "$OPENSHIFT_REPO_DIR"/.openshift/action_hooks/secure_db.py | tee ${OPENSHIFT_DATA_DIR}/CREDENTIALS
fi
